### ISSUE TITLE
Connecting to local OLAP Server

### ISSUE THREAD

**Issue by Snowpile** [may-day/olap#10]
I looked through the readme and have attempted to log in to a local OLAP Server. From the Readme and everywhere I've looked online I don't know if this is able to connect to a local OLAP or only through http?

My code is probably wrong?

`location = 'SQLOLAPCP'`
`username = 'username'`
`password = 'password'`
`provider = xmla.XMLAProvider()`
`cxn = provider.connect(location=location, username=username, password=password)`
`print cxn.getOLAPSource()`

This code gives me the following error:
No handlers could be found for logger "olap.xmla.requests_kerberosauth"
XMLASource:{}

Thanks for your help!

**Comment by may-day** [comment]
Hi, it is through http only.
