### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by waltonereed** [may-day/olap#9]
I'm trying to install the module but get an error message after entering "**pip install xmla**". I'm completely new to Python, so I'm assuming user error (and forgive my ignorance), but any feedback would be fantastic. See screenshot.
![capture](https://cloud.githubusercontent.com/assets/25827972/23036147/4a0dfc5a-f447-11e6-8673-7f550853847c.PNG)

**Comment by may-day** [comment]
- make sure you are using python2 (anaconda3 defaults to python3, but you can make an environment in anaconda3 that uses python2 like so: ```conda create -n mypy27 -python=2.7 anaconda```)
- make sure you don't have your PATH environment pointing to another python3 environment where it might find "pip" first (happend to me:)

**Comment by waltonereed** [comment]
Hi @may-day , that did the trick. Thank you so much!
